/*
Copyright © 2018 inwinSTACK.inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	inwinstackv1 "github.com/inwinstack/blended/apis/inwinstack/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNATs implements NATInterface
type FakeNATs struct {
	Fake *FakeInwinstackV1
	ns   string
}

var natsResource = schema.GroupVersionResource{Group: "inwinstack.com", Version: "v1", Resource: "nats"}

var natsKind = schema.GroupVersionKind{Group: "inwinstack.com", Version: "v1", Kind: "NAT"}

// Get takes name of the nAT, and returns the corresponding nAT object, and an error if there is any.
func (c *FakeNATs) Get(name string, options v1.GetOptions) (result *inwinstackv1.NAT, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(natsResource, c.ns, name), &inwinstackv1.NAT{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inwinstackv1.NAT), err
}

// List takes label and field selectors, and returns the list of NATs that match those selectors.
func (c *FakeNATs) List(opts v1.ListOptions) (result *inwinstackv1.NATList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(natsResource, natsKind, c.ns, opts), &inwinstackv1.NATList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &inwinstackv1.NATList{ListMeta: obj.(*inwinstackv1.NATList).ListMeta}
	for _, item := range obj.(*inwinstackv1.NATList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested nATs.
func (c *FakeNATs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(natsResource, c.ns, opts))

}

// Create takes the representation of a nAT and creates it.  Returns the server's representation of the nAT, and an error, if there is any.
func (c *FakeNATs) Create(nAT *inwinstackv1.NAT) (result *inwinstackv1.NAT, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(natsResource, c.ns, nAT), &inwinstackv1.NAT{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inwinstackv1.NAT), err
}

// Update takes the representation of a nAT and updates it. Returns the server's representation of the nAT, and an error, if there is any.
func (c *FakeNATs) Update(nAT *inwinstackv1.NAT) (result *inwinstackv1.NAT, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(natsResource, c.ns, nAT), &inwinstackv1.NAT{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inwinstackv1.NAT), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNATs) UpdateStatus(nAT *inwinstackv1.NAT) (*inwinstackv1.NAT, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(natsResource, "status", c.ns, nAT), &inwinstackv1.NAT{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inwinstackv1.NAT), err
}

// Delete takes name of the nAT and deletes it. Returns an error if one occurs.
func (c *FakeNATs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(natsResource, c.ns, name), &inwinstackv1.NAT{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNATs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(natsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &inwinstackv1.NATList{})
	return err
}

// Patch applies the patch and returns the patched nAT.
func (c *FakeNATs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *inwinstackv1.NAT, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(natsResource, c.ns, name, data, subresources...), &inwinstackv1.NAT{})

	if obj == nil {
		return nil, err
	}
	return obj.(*inwinstackv1.NAT), err
}
